name: Deploy and build App

on:
  push:
    
jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [18]
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup PNPM
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        # deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out
        allow_empty_commit: true
        user_name: "github-actions[bot]"
        user_email: "github-actions[bot]@users.noreply.github.com"
